import { format } from 'date-fns';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { DistributorProfile, Order, ShopkeeperProfile } from '../types';

interface InvoicePdfInput {
  order: Order;
  distributor: DistributorProfile;
  shopkeeper?: ShopkeeperProfile | null;
  distributorPhone?: string;
  distributorEmail?: string;
  shopkeeperPhone?: string;
  shopkeeperEmail?: string;
  language?: 'hinglish' | 'english' | 'hindi';
}

function safeText(value: string | undefined, fallback: string) {
  const v = (value || '').trim();
  return v.length > 0 ? v : fallback;
}

export function downloadInvoicePdf({
  order,
  distributor,
  shopkeeper,
  distributorPhone,
  distributorEmail,
  shopkeeperPhone,
  shopkeeperEmail,
  language = 'hinglish',
}: InvoicePdfInput) {
  const i18n = {
    hinglish: {
      billedTo: 'Billed To',
      shippedTo: 'Shipped To',
      invoice: 'INVOICE',
      invoiceNo: 'Invoice No',
      totalItems: 'Total Items',
      totalAmount: 'Total Amount',
      generatedBy: 'Generated by Dairy Walla',
      generatedOn: 'Generated on',
      owner: 'Owner',
      address: 'Address',
      gst: 'GST',
      phone: 'Phone',
      email: 'Email',
      orderDate: 'Order Date',
      notProvided: 'Not provided',
      shopName: 'Shop Name',
      shopkeeper: 'Shopkeeper',
      distributorFallback: 'Distributor',
      distributorInvoiceFallback: 'Dairy distributor invoice',
      smartTagline: 'Smart dairy ordering',
      headers: ['S.No', 'Product', 'Brand', 'Unit', 'Qty', 'Rate', 'Amount'] as string[],
    },
    english: {
      billedTo: 'Billed To',
      shippedTo: 'Shipped To',
      invoice: 'INVOICE',
      invoiceNo: 'Invoice No',
      totalItems: 'Total Items',
      totalAmount: 'Total Amount',
      generatedBy: 'Generated by Dairy Walla',
      generatedOn: 'Generated on',
      owner: 'Owner',
      address: 'Address',
      gst: 'GST',
      phone: 'Phone',
      email: 'Email',
      orderDate: 'Order Date',
      notProvided: 'Not provided',
      shopName: 'Shop Name',
      shopkeeper: 'Shopkeeper',
      distributorFallback: 'Distributor',
      distributorInvoiceFallback: 'Dairy distributor invoice',
      smartTagline: 'Smart dairy ordering',
      headers: ['S.No', 'Product', 'Brand', 'Unit', 'Qty', 'Rate', 'Amount'] as string[],
    },
    hindi: {
      billedTo: 'Bill Kisko',
      shippedTo: 'Delivery Kisko',
      invoice: 'BILL',
      invoiceNo: 'Bill Number',
      totalItems: 'Total Item',
      totalAmount: 'Kul Rakam',
      generatedBy: 'Dairy Walla se banaya gaya',
      generatedOn: 'Banaya gaya',
      owner: 'Maalik',
      address: 'Pata',
      gst: 'GST',
      phone: 'Phone',
      email: 'Email',
      orderDate: 'Order Date',
      notProvided: 'Uplabdh nahi',
      shopName: 'Dukaan Naam',
      shopkeeper: 'Dukaan Malik',
      distributorFallback: 'Vitarak',
      distributorInvoiceFallback: 'Dairy bill',
      smartTagline: 'Smart dairy ordering',
      headers: ['Kr.', 'Product', 'Brand', 'Unit', 'Qty', 'Rate', 'Amount'] as string[],
    },
  }[language];
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 12;
  const contentW = pageW - margin * 2;

  const line = [220, 220, 220] as const;
  const muted = [105, 105, 105] as const;
  const dark = [28, 28, 28] as const;
  const brand = [22, 163, 74] as const;

  doc.setDrawColor(...line);
  doc.rect(margin, margin, contentW, pageH - margin * 2);

  doc.setTextColor(232, 232, 232);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('DAIRY WALLA', pageW - 5.7, pageH / 2, { angle: 90, align: 'center' });

  let y = margin + 3;
  const headerH = 26;

  doc.setDrawColor(...line);
  doc.roundedRect(margin + 2, y, contentW - 4, headerH, 1.5, 1.5);
  doc.setFillColor(249, 249, 249);
  doc.roundedRect(margin + 2, y, contentW - 4, headerH, 1.5, 1.5, 'F');

  const leftX = margin + 6;
  const rightBoxW = 56;
  const rightX = margin + contentW - rightBoxW - 6;

  doc.setTextColor(...dark);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text(safeText(distributor.businessName, i18n.distributorFallback), leftX, y + 8);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.2);
  doc.setTextColor(...muted);
  const distAddress = [distributor.address, distributor.city].filter(Boolean).join(', ');
  const distLine = [
    distributor.ownerName ? `${i18n.owner}: ${distributor.ownerName}` : '',
    distAddress ? `${i18n.address}: ${distAddress}` : '',
    distributor.gst ? `${i18n.gst}: ${distributor.gst}` : '',
  ].filter(Boolean).join('  |  ');
  doc.text(distLine || i18n.distributorInvoiceFallback, leftX, y + 14.3, { maxWidth: contentW - rightBoxW - 18 });
  doc.text(`${i18n.phone}: ${safeText(distributorPhone, i18n.notProvided)}  |  ${i18n.email}: ${safeText(distributorEmail, i18n.notProvided)}`, leftX, y + 19.4, {
    maxWidth: contentW - rightBoxW - 18,
  });

  doc.setDrawColor(...line);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(rightX, y + 4, rightBoxW, 17, 1.5, 1.5, 'FD');
  doc.setFillColor(...brand);
  doc.circle(rightX + 6.5, y + 12.5, 3.9, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.text('DW', rightX + 6.5, y + 13.6, { align: 'center' });
  doc.setTextColor(...dark);
  doc.setFontSize(9.8);
  doc.text('Dairy Walla', rightX + 12, y + 11.1);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.1);
  doc.setTextColor(...muted);
  doc.text(i18n.smartTagline, rightX + 12, y + 15.2);

  y += headerH + 5;

  const metaBoxH = 28;
  const gap = 4;
  const halfW = (contentW - gap - 4) / 2;
  const billX = margin + 2;
  const shipX = billX + halfW + gap;

  doc.setDrawColor(...line);
  doc.roundedRect(billX, y, halfW, metaBoxH, 1.2, 1.2);
  doc.roundedRect(shipX, y, halfW, metaBoxH, 1.2, 1.2);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...dark);
  doc.text(i18n.billedTo, billX + 3, y + 5.2);
  doc.text(i18n.shippedTo, shipX + 3, y + 5.2);

  const shopAddress = [shopkeeper?.address, shopkeeper?.city].filter(Boolean).join(', ');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.2);
  doc.setTextColor(...muted);
  doc.text(safeText(order.shopName, i18n.shopName), billX + 3, y + 10.2);
  doc.text(safeText(order.shopkeeperName, i18n.shopkeeper), billX + 3, y + 14.4);
  doc.text(safeText(shopAddress, i18n.notProvided), billX + 3, y + 18.6, { maxWidth: halfW - 6 });
  doc.text(`${i18n.phone}: ${safeText(shopkeeperPhone, i18n.notProvided)}`, billX + 3, y + 22.8);
  doc.text(safeText(order.shopName, i18n.shopName), shipX + 3, y + 10.2);
  doc.text(safeText(shopAddress, i18n.notProvided), shipX + 3, y + 14.4, { maxWidth: halfW - 6 });
  doc.text(`${i18n.email}: ${safeText(shopkeeperEmail, i18n.notProvided)}`, shipX + 3, y + 18.6, { maxWidth: halfW - 6 });
  doc.text(`${i18n.orderDate}: ${format(new Date(order.placedAt), 'dd MMM yyyy')}`, shipX + 3, y + 22.8);

  y += metaBoxH + 7.5;

  doc.setDrawColor(...line);
  doc.roundedRect(margin + 2, y, contentW - 4, 12, 1.2, 1.2);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...dark);
  doc.text(i18n.invoice, margin + 5, y + 7.6);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(...muted);
  doc.text(`${i18n.invoiceNo}: ${order.id.slice(-8).toUpperCase()}`, margin + contentW - 58, y + 5);
  doc.text(`${i18n.totalItems}: ${order.items.length}`, margin + contentW - 58, y + 9.4);

  const rows = order.items.map((item, idx) => ([
    String(idx + 1),
    item.productName,
    item.brand,
    item.unit,
    String(item.quantity),
    `Rs ${item.unitPrice.toLocaleString()}`,
    `Rs ${(item.quantity * item.unitPrice).toLocaleString()}`,
  ]));

  autoTable(doc, {
    startY: y + 15,
    head: [i18n.headers],
    body: rows,
    margin: { left: margin + 2, right: margin + 2 },
    theme: 'grid',
    styles: {
      font: 'helvetica',
      fontSize: 8,
      cellPadding: { top: 1.8, right: 1.8, bottom: 1.8, left: 1.8 },
      lineWidth: 0.2,
      lineColor: [228, 228, 228],
      textColor: [35, 35, 35],
      valign: 'middle',
    },
    headStyles: {
      fillColor: [246, 246, 246],
      textColor: [45, 45, 45],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [252, 252, 252],
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 54 },
      2: { cellWidth: 30 },
      3: { cellWidth: 16, halign: 'center' },
      4: { cellWidth: 14, halign: 'right' },
      5: { cellWidth: 26, halign: 'right' },
      6: { cellWidth: 30, halign: 'right' },
    },
  });

  const tableEndY = (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? y + 70;
  const footerTop = Math.min(tableEndY + 6, pageH - 34);

  doc.setDrawColor(...line);
  doc.roundedRect(margin + 2, footerTop, contentW - 4, 16, 1.2, 1.2);

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...muted);
  doc.setFontSize(8);
  doc.text(`${i18n.generatedOn} ${format(new Date(), 'dd MMM yyyy, hh:mm a')}`, margin + 5, footerTop + 6.3);
  doc.text(i18n.generatedBy, margin + 5, footerTop + 10.8);

  doc.setFillColor(247, 251, 247);
  doc.setDrawColor(200, 225, 208);
  doc.roundedRect(pageW - margin - 68, footerTop + 2, 62, 12, 1.2, 1.2, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(80, 80, 80);
  doc.text(i18n.totalAmount, pageW - margin - 64, footerTop + 6.7);
  doc.setTextColor(...brand);
  doc.setFontSize(12);
  doc.text(`Rs ${order.total.toLocaleString()}`, pageW - margin - 8, footerTop + 11.2, { align: 'right' });

  doc.save(`invoice-${order.id.slice(-8)}.pdf`);
}
